Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'MhsDesign.LiveInspectorJsEvents:JsEvents':
            resource: resource://MhsDesign.LiveInspectorJsEvents/Public/JsEvents/Plugin.js
